// packages/adapters/web-component/src/adapt.ts
// packages/adapters/web-component/src/adapt.ts
import {
  getModuleDeclaration,
  type Prototype,
  type ScrollProjectionPreference,
} from '@proto.ui/core';
import { PropsBaseType } from '@proto.ui/types';

import { type RawPropsSource } from '@proto.ui/module-props';

import {
  createHostWiring,
  createHostSurfaceProjection,
  createEventGate,
  createDefaultWebColorSchemeSource,
  createScopedExposesReader,
  createWebProtoEventRouter,
  createViewEpochOwner,
  scheduleAfterWebLayout,
  type HostSurfaceProjection,
  type LogicalInstanceToken,
  type ProtoAdapterProps,
} from '@proto.ui/adapter-base';
import {
  createZIndexOverlayLayerScheduler,
  type OverlayLayerScheduler,
  type OverlayZIndexLayerSchedulerOptions,
} from '@proto.ui/module-overlay';
import {
  resolveWebTextControlLocalName,
  TEXT_CONTROL_DECLARATION,
  type WebTextControl,
} from '@proto.ui/module-text-control';
import { IMAGE_VIEW_DECLARATION, resolveWebImageLocalName } from '@proto.ui/module-image-view';

import {
  bindController,
  bindElementSurfaceProjection,
  getElementProps,
  setElementProps,
  unbindController,
} from './props';
import { SlotProjector } from './slot-projector';
import { createOwnedTwTokenApplier } from './feedback-style';
import { installDebugHooks, removeDebugHooks } from './debug/hooks';
import {
  installDefaultHostDisplay,
  PUI_VIEW_DETACHED_ATTR,
  type HostDisplayController,
} from './host-display';
import { createDefaultMetaGetter } from './platform/meta';
import {
  createLogicalInstance,
  bindLogicalEventTarget,
  resolveLogicalTriggerEventRouteForTarget,
  isLogicalEventRouteCandidate,
  markProtoInstance,
  unbindProtoInstance,
  unbindLogicalEventTarget,
} from './platform/instance-tree';
import { createWebEffectsPort } from './runtime/effects-port';
import { createShadowTextControlSurface } from './shadow-text-control-surface';
import { createWebComponentModules, createWebComponentOwnerModules } from './runtime/modules';
import { createWebComponentHostSession } from './runtime/session';
import { createShadowOwnerShell, type ShadowOwnerShell } from './shadow-owner-shell';
import { normalizeShadowProfile, type WebComponentShadowSplitOptions } from './shadow-profile';
import { createShadowSplitResources, type ShadowSplitResources } from './shadow-split-resources';
import { createShadowSplitEffectsPort } from './shadow-split-effects';
import { createPortalConcealBarrier } from './portal-conceal';
import type { WebComponentAdapterConstructor } from './types';
import type {
  RuntimeCheckpoint,
  RuntimeController,
  RuntimeLifecycleEvent,
} from '@proto.ui/runtime';

export { __WC_DEBUG_SYS } from './debug/hooks';
export type { ShadowStyleArtifactV1 } from './shadow-style-artifact';
export type { ShadowColorSchemeSource } from './shadow-color-scheme-environment';
export type { WebComponentShadowSplitOptions } from './shadow-profile';
export type {
  WebComponentAdapterConstructor,
  WebComponentAdapterHandle,
  WebComponentAdapterElement,
} from './types';

function assertKebabCase(tag: string) {
  if (!tag.includes('-') || tag.toLowerCase() !== tag) {
    throw new Error(`[WC Adapter] custom element name must be kebab-case and contain '-': ${tag}`);
  }
}

export interface WebComponentAdapterOptions<Props extends PropsBaseType = PropsBaseType> {
  shadow?: boolean | WebComponentShadowSplitOptions;
  register?: boolean;
  registerAs?: string;
  getProps?: (el: HTMLElement) => Partial<Props> | null | undefined;
  schedule?: (task: () => void) => void;
  getMeta?: (key: string) => unknown;
  diagnostics?: {
    onLifecycleEvent?: (event: RuntimeLifecycleEvent) => void;
    /** @deprecated Use onLifecycleEvent. */
    onLifecycleCheckpoint?: (cp: RuntimeCheckpoint) => void;
  };
  exposeStateWebMode?: {
    allowContinuousAttr?: boolean;
    allowStringVar?: boolean;
  };
  scrollProjection?: ScrollProjectionPreference;
  overlayLayer?:
    | (OverlayZIndexLayerSchedulerOptions & {
        scheduler?: OverlayLayerScheduler;
      })
    | undefined;
}

const SHARED_OVERLAY_LAYER_SCHEDULER = createZIndexOverlayLayerScheduler();
const NOTIFY_FOCUS_TARGET_READY = Symbol('proto-ui.notify-focus-target-ready');

export function AdaptToWebComponent<TProto extends Prototype<any, any>>(
  proto: TProto,
  opt: WebComponentAdapterOptions<ProtoAdapterProps<TProto>> = {}
): WebComponentAdapterConstructor<TProto> {
  type Props = ProtoAdapterProps<TProto>;
  const register = opt.register ?? true;
  const tagName = opt.registerAs ?? proto.name;
  assertKebabCase(tagName);
  const textControl = getModuleDeclaration(proto, TEXT_CONTROL_DECLARATION)?.config;
  const imageView = getModuleDeclaration(proto, IMAGE_VIEW_DECLARATION)?.config;

  const profile = normalizeShadowProfile(opt.shadow);
  const split = typeof profile === 'object' ? profile : null;
  const shadow = profile !== false;
  if (split && imageView) {
    throw new Error('[WC Adapter] shadow split does not support image-view declarations.');
  }
  if (
    split &&
    textControl &&
    !split.styleArtifact.cssText.includes('--pui-split-native-text-recipe: l1;')
  ) {
    throw new Error('[WC Adapter] native text recipe is absent; regenerate the CLI companion.');
  }
  const getProps = opt.getProps ?? (() => ({}) as Partial<Props>);
  const schedule = opt.schedule ?? ((task) => queueMicrotask(task));
  const getMeta = opt.getMeta ?? createDefaultMetaGetter();
  // Split reserves colorScheme for its retained environment, not the document getter.
  const colorSchemeSource =
    split || opt.getMeta ? undefined : createDefaultWebColorSchemeSource(getMeta);
  const exposeStateWebMode = opt.exposeStateWebMode;
  const scrollProjection = opt.scrollProjection;
  const MAX_FOCUS_TARGET_RETRIES = 3;

  const hasCustomOverlayLayerConfig =
    !!opt.overlayLayer &&
    (typeof opt.overlayLayer.baseZIndex !== 'undefined' ||
      typeof opt.overlayLayer.step !== 'undefined' ||
      typeof opt.overlayLayer.roleOffsets !== 'undefined');
  const overlayLayerScheduler =
    opt.overlayLayer?.scheduler ??
    (hasCustomOverlayLayerConfig
      ? createZIndexOverlayLayerScheduler({
          baseZIndex: opt.overlayLayer?.baseZIndex,
          step: opt.overlayLayer?.step,
          roleOffsets: opt.overlayLayer?.roleOffsets,
        })
      : SHARED_OVERLAY_LAYER_SCHEDULER);

  class ProtoElement extends HTMLElement {
    private _mountedOnce = false;
    private _runtimeGeneration = 0;
    private _instanceToken: LogicalInstanceToken;
    private _invokeUnmounted: (() => void | Promise<void>) | null = null;
    private _splitOwnerDisposing = false;
    private _disconnectVersion = 0;
    private _pendingOwnedTokens: string[] | null = null;
    private _controller: RuntimeController | null = null;
    private _focusTargetReadyListeners = new Set<() => void>();
    private _focusTargetRetryScheduled = false;
    private _focusTargetRetryCount = 0;

    private _root: Element | ShadowRoot;
    private _shadowOwnerShell: ShadowOwnerShell | null;
    private _splitResources: ShadowSplitResources | null = null;
    private _initializationCleanup: (() => void) | null = null;
    private _portalConceal = createPortalConcealBarrier(this);
    private _slotProjector: SlotProjector | null = null;
    private _hostDisplay: HostDisplayController | null = null;
    private _textControlTarget: WebTextControl | null = null;
    private _imageViewTarget: HTMLImageElement | null = null;
    private _surfaceProjection: HostSurfaceProjection<HTMLElement>;

    private _applier: ReturnType<typeof createOwnedTwTokenApplier> | null = null;
    private _exposes: Record<string, unknown> = {};

    constructor() {
      super();
      this._root = shadow ? (this.attachShadow({ mode: 'open' }) as ShadowRoot) : this;
      this._shadowOwnerShell = shadow ? createShadowOwnerShell(this._root as ShadowRoot) : null;
      if (textControl && imageView) {
        throw new Error(
          '[WC Adapter] text-control and image-view declarations cannot share a root.'
        );
      }
      if (textControl) {
        this._textControlTarget = document.createElement(
          resolveWebTextControlLocalName(textControl)
        );
        this._textControlTarget.setAttribute('part', 'control');
      }
      if (imageView) {
        this._imageViewTarget = document.createElement(resolveWebImageLocalName());
        this._imageViewTarget.setAttribute('part', 'image');
      }
      this._surfaceProjection = createHostSurfaceProjection<HTMLElement>(
        this,
        split ? null : (this._textControlTarget ?? this._imageViewTarget ?? this)
      );
      bindElementSurfaceProjection(this, this._surfaceProjection);
      this._instanceToken = createLogicalInstance(proto as Prototype<any>);
      markProtoInstance(this, proto as Prototype<any>, this._instanceToken);
    }

    override focus(options?: FocusOptions): void {
      if (this._textControlTarget) {
        this._textControlTarget.focus(options);
        return;
      }
      super.focus(options);
    }

    override blur(): void {
      if (this._textControlTarget) {
        this._textControlTarget.blur();
        return;
      }
      super.blur();
    }

    connectedCallback() {
      // Reuse is valid for synchronous moves, not once terminal teardown starts.
      // The predecessor owns host-wide resources until its complete cleanup;
      // coalesce reconnects and initialize only after it can no longer write.
      if (split && this._splitOwnerDisposing) return;
      const initializing = !this._mountedOnce;
      try {
        this._connectOwner();
      } catch (error) {
        if (split && initializing) {
          // A failed activation is retryable on a later connection, never a half-owner.
          try {
            this._initializationCleanup?.();
          } catch {}
          this._initializationCleanup = null;
          try {
            this._releaseSplitResources();
          } catch {}
          this._hostDisplay?.disconnect();
          this._hostDisplay = null;
          unbindController(this);
          removeDebugHooks(this);
          unbindProtoInstance(this._instanceToken, this);
          this._controller = null;
          this._invokeUnmounted = null;
          this._exposes = {};
          this._mountedOnce = false;
          this.setAttribute(PUI_VIEW_DETACHED_ATTR, '');
        }
        throw error;
      }
    }

    private _releaseSplitResources() {
      const resources = this._splitResources;
      this._splitResources = null;
      try {
        this._surfaceProjection.setSurfaceTarget(null);
      } finally {
        resources?.dispose();
      }
    }

    private _connectOwner() {
      this._focusTargetRetryCount = 0;

      if (this._mountedOnce) {
        // Refresh the logical parent link after a synchronous DOM move.
        markProtoInstance(this, proto as Prototype<any>, this._instanceToken);
        if (this._pendingOwnedTokens?.length) {
          this._applier?.apply(this._pendingOwnedTokens);
        }
        this._hostDisplay?.sync();
        this._pendingOwnedTokens = null;
        this._controller?.update();
        schedule(() => this[NOTIFY_FOCUS_TARGET_READY]());
        return;
      }
      if (this._runtimeGeneration > 0) {
        this._instanceToken = createLogicalInstance(proto as Prototype<any>);
      }
      // The constructor ran before the element had a DOM parent.
      markProtoInstance(this, proto as Prototype<any>, this._instanceToken);
      this._runtimeGeneration += 1;
      this._mountedOnce = true;

      const thisEl = this;
      const thisRoot = this._root;
      thisEl.setAttribute('data-pui-root', '');
      if (split) {
        this._splitResources = createShadowSplitResources({
          host: thisEl,
          shell: this._shadowOwnerShell!,
          artifact: split.styleArtifact,
          colorSchemeSource: split.colorSchemeSource,
          baseGetMeta: getMeta,
          factories: this._textControlTarget
            ? {
                createSurface: (shell) =>
                  createShadowTextControlSurface(shell, this._textControlTarget!),
              }
            : undefined,
        });
        this._splitResources.surface.element.setAttribute(
          'part',
          textControl ? 'control surface' : 'surface'
        );
        this._surfaceProjection.setSurfaceTarget(this._splitResources.surface.element);
      }
      const splitResources = this._splitResources;
      const ownerGetMeta = splitResources?.getMeta ?? getMeta;
      this._hostDisplay = installDefaultHostDisplay(thisEl, {
        displayOwner: split ? 'presentation' : 'fallback',
      });

      const rawPropsSource: RawPropsSource<Props> = {
        debugName: `${tagName}#raw-props`,
        get(): Readonly<Props & PropsBaseType> {
          const p = getElementProps(thisEl) ?? getProps(thisEl) ?? ({} as Partial<Props>);
          return p as unknown as Readonly<Props & PropsBaseType>;
        },
        subscribe(cb) {
          const mo = new MutationObserver((records) => {
            for (const r of records) {
              if (r.type === 'attributes') {
                cb();
                break;
              }
            }
          });

          mo.observe(thisEl, { attributes: true });
          return () => mo.disconnect();
        },
      };

      let runFocusCallbackScope: ((fn: () => void) => void) | null = null;
      const runInCallbackScope = (fn: () => void) => {
        if (runFocusCallbackScope) {
          runFocusCallbackScope(fn);
          return;
        }
        fn();
      };
      const scopedExposesReader = createScopedExposesReader(() => runFocusCallbackScope);
      const setExposes = (record: Record<string, unknown>) => {
        this._exposes = record;
      };

      const owner = createViewEpochOwner<Props>({ prototypeName: tagName });
      this._initializationCleanup = () => {
        void owner.dispose().catch(() => {});
      };
      let currentEventGate: ReturnType<typeof createEventGate> | null = null;
      let currentRouter: ReturnType<typeof createWebProtoEventRouter> | null = null;

      const clearSlotProjector = () => {
        this._slotProjector?.disconnect();
        this._slotProjector = null;
      };

      const setViewDetached = (detached: boolean) => {
        thisEl.toggleAttribute(PUI_VIEW_DETACHED_ATTR, detached);
        if (detached) {
          currentEventGate?.disable();
          return;
        }
        schedule(() => {
          if (!thisEl.isConnected || thisEl.hasAttribute(PUI_VIEW_DETACHED_ATTR)) return;
          currentEventGate?.enable();
          thisEl[NOTIFY_FOCUS_TARGET_READY]();
          for (const descendant of thisEl.querySelectorAll<ProtoElement>('[data-pui-root]')) {
            descendant[NOTIFY_FOCUS_TARGET_READY]?.();
          }
        });
      };

      const releaseRenderedChildren = () => {
        if (shadow) {
          if (splitResources) splitResources.surface.clearRenderedChildren();
          else this._shadowOwnerShell?.clearRenderedChildren();
          clearSlotProjector();
          return;
        }

        if (this._imageViewTarget?.parentNode) {
          this._imageViewTarget.parentNode.removeChild(this._imageViewTarget);
        }

        const projector = this._slotProjector;
        if (!projector) return;
        const externalChildren = projector.collectSlotPoolBeforeCommit();
        projector.disconnect();
        this._slotProjector = null;
        thisEl.replaceChildren(...externalChildren);
      };

      const createHostSession = (wiring: ReturnType<typeof createHostWiring>) =>
        createWebComponentHostSession({
          proto,
          tagName,
          shadow,
          host: thisEl,
          root: thisRoot,
          shadowOwnerShell: this._shadowOwnerShell,
          shadowViewTarget: splitResources?.surface,
          schedule,
          rawPropsSource,
          textControlTarget: this._textControlTarget,
          imageViewTarget: this._imageViewTarget,
          wiring,
          eventGate: {
            enable: () => {
              if (!thisEl.hasAttribute(PUI_VIEW_DETACHED_ATTR)) currentEventGate?.enable();
            },
            disable: () => currentEventGate?.disable(),
            dispose: () => owner.disposeView(),
          },
          router: {
            dispose: () => owner.disposeView(),
          },
          onLifecycleCheckpoint: opt.diagnostics?.onLifecycleCheckpoint,
          onLifecycleEvent: opt.diagnostics?.onLifecycleEvent,
          getSlotProjector: () => this._slotProjector,
          ensureSlotProjector: () => {
            if (!this._slotProjector) this._slotProjector = new SlotProjector(thisEl);
            return this._slotProjector;
          },
          clearSlotProjector,
          onAfterUnmount: () => {
            scopedExposesReader.invalidate();
            runFocusCallbackScope = null;
            this._exposes = {};
            this._applier?.clear();
            this._applier = null;
            this._hostDisplay?.disconnect();
            this._hostDisplay = null;
            try {
              if (splitResources && this._splitResources === splitResources)
                this._releaseSplitResources();
            } finally {
              unbindController(this);
              removeDebugHooks(this);
            }
          },
          initialMount: 'manual',
        });

      const attachView = () => {
        if (owner.hasView) {
          setViewDetached(false);
          return;
        }

        if (splitResources && this._textControlTarget)
          splitResources.surface.replaceRenderedChildren([this._textControlTarget]);
        const splitEffects = splitResources
          ? createShadowSplitEffectsPort({
              host: thisEl,
              surface: splitResources.surface.element,
              artifact: splitResources.artifact.artifact,
              prototypeName: proto.name,
            })
          : null;
        const eventGate = createEventGate();
        const router = createWebProtoEventRouter({
          rootEl: thisEl,
          focusEventTarget: this._textControlTarget ?? undefined,
          instanceToken: this._instanceToken,
          resolveSemanticEventRoute: resolveLogicalTriggerEventRouteForTarget,
          isSemanticEventRouteCandidate: isLogicalEventRouteCandidate,
          globalEl: window,
          isEnabled: () => eventGate.isEnabled?.() ?? true,
        });
        bindLogicalEventTarget(this._instanceToken, router.rootTarget);
        const applier = splitEffects
          ? null
          : createOwnedTwTokenApplier(this._textControlTarget ?? this._imageViewTarget ?? thisEl, {
              onChange: () => {
                this._hostDisplay?.sync();
              },
            });
        currentEventGate = eventGate;
        currentRouter = router;
        this._applier = applier;
        // Focus/blur subscriptions bind directly to the physical editor.
        // A second host listener would see Shadow-retargeted focus and could
        // overwrite native :focus-visible with the shell's false result.

        let disposed = false;
        const disposeView = () => {
          if (disposed) return;
          disposed = true;
          eventGate.disable();
          eventGate.dispose();
          unbindLogicalEventTarget(this._instanceToken, router.rootTarget);
          router.dispose();
          applier?.clear();
          splitEffects?.dispose();
          releaseRenderedChildren();
          if (currentEventGate === eventGate) currentEventGate = null;
          if (currentRouter === router) currentRouter = null;
          if (this._applier === applier) this._applier = null;
          this._hostDisplay?.sync();
        };

        try {
          owner.attachView({
            modules: createWebComponentModules({
              el: thisEl,
              instanceToken: this._instanceToken,
              router,
              rawPropsSource,
              effectsPort: splitEffects ?? createWebEffectsPort(applier!),
              getMeta: ownerGetMeta,
              colorSchemeSource,
              textControlTarget: this._textControlTarget,
              imageViewTarget: this._imageViewTarget,
              exposeStateWebMode,
              scrollProjection,
              setExposes,
              runInCallbackScope,
              isViewReady: () =>
                thisEl.isConnected && !thisEl.closest(`[${PUI_VIEW_DETACHED_ATTR}]`),
              subscribeTargetReady: (listener: () => void) => {
                this._focusTargetReadyListeners.add(listener);
                return () => this._focusTargetReadyListeners.delete(listener);
              },
              retryTargetReady: () => {
                if (
                  this._focusTargetRetryScheduled ||
                  this._focusTargetRetryCount >= MAX_FOCUS_TARGET_RETRIES
                ) {
                  return;
                }
                this._focusTargetRetryScheduled = true;
                this._focusTargetRetryCount += 1;
                scheduleAfterWebLayout(
                  this,
                  () => {
                    this._focusTargetRetryScheduled = false;
                    this[NOTIFY_FOCUS_TARGET_READY]();
                  },
                  schedule
                );
              },
              overlayLayerScheduler,
            }),
            disposeView,
            createSession: createHostSession,
          });
        } catch (error) {
          disposeView();
          throw error;
        }
        setViewDetached(false);
      };

      let latestIntentVersion = 0;
      let reconciliation = Promise.resolve();
      let initializingOwner = true;
      let initialPresent = true;
      const reconcileIntent = (snapshot: { present: boolean }) => {
        if (initializingOwner) {
          initialPresent = snapshot.present;
          return;
        }
        const wasConcealing = this._portalConceal.cancel();
        if (!snapshot.present) setViewDetached(true);
        const requestVersion = ++latestIntentVersion;
        if (snapshot.present && wasConcealing && owner.hasView) {
          // The retained epoch never unmounted. Reveal it immediately so a
          // newer open/focus request is not queued behind the canceled barrier.
          setViewDetached(false);
          return;
        }
        queueMicrotask(() => {
          reconciliation = reconciliation
            .then(async () => {
              if (
                requestVersion !== latestIntentVersion ||
                !thisEl.isConnected ||
                this._controller !== hostSession.controller
              ) {
                return;
              }
              if (snapshot.present) {
                attachView();
              } else if (owner.hasView) {
                const conceal = this._portalConceal.wait();
                if (conceal) await conceal;
                if (
                  requestVersion !== latestIntentVersion ||
                  !thisEl.isConnected ||
                  this._controller !== hostSession.controller
                )
                  return;
                await owner.detachView();
              }
            })
            .catch((error) => {
              queueMicrotask(() => {
                throw error;
              });
            });
        });
      };

      const ownerModules = createWebComponentOwnerModules({
        el: thisEl,
        instanceToken: this._instanceToken,
        rawPropsSource,
        getMeta: ownerGetMeta,
        colorSchemeSource,
        textControlTarget: this._textControlTarget,
        imageViewTarget: this._imageViewTarget,
        exposeStateWebMode,
        setExposes,
        runInCallbackScope,
        overlayLayerScheduler,
      });
      const hostSession = owner.initialize({
        modules: ownerModules,
        createSession: createHostSession,
        onViewIntent: reconcileIntent,
      });
      initializingOwner = false;
      runFocusCallbackScope = hostSession.invokeInCallbackScope;

      if (initialPresent) attachView();
      else setViewDetached(true);

      const { controller, kernel } = hostSession;
      if (kernel && kernel.run) {
        (kernel.run as any).host = { get: () => thisEl };
      }

      installDebugHooks(thisEl, hostSession.caps);

      (this as any).update = () => controller.update();

      (this as any).getExposes = () => {
        if (!this.isConnected) return {};
        return scopedExposesReader.read(this._exposes ?? {});
      };

      (this as unknown as { setProps?(v: Record<string, unknown>): void }).setProps = (
        next: Record<string, unknown>
      ) => {
        setElementProps(thisEl, next);
        controller.update();
      };

      this._controller = controller;
      bindController(this, controller);

      this._invokeUnmounted = () => owner.dispose();
      this._initializationCleanup = null;
    }

    private [NOTIFY_FOCUS_TARGET_READY](): void {
      for (const listener of Array.from(this._focusTargetReadyListeners)) listener();
      const active = this.ownerDocument.activeElement;
      if (
        active === this ||
        this.contains(active) ||
        (this.shadowRoot?.activeElement ?? null) !== null
      ) {
        this._focusTargetRetryCount = 0;
      }
    }

    disconnectedCallback() {
      this._pendingOwnedTokens = this._applier ? Array.from(this._applier.getOwned()) : null;
      this._applier?.clear();
      this._hostDisplay?.sync();

      const disconnectVersion = ++this._disconnectVersion;

      queueMicrotask(async () => {
        if (this._disconnectVersion !== disconnectVersion) {
          if (this._pendingOwnedTokens?.length) {
            this._applier?.apply(this._pendingOwnedTokens);
          }
          this._hostDisplay?.sync();
          this._pendingOwnedTokens = null;
          return;
        }
        if (this.isConnected) {
          this._pendingOwnedTokens = null;
          return;
        }

        if (this._invokeUnmounted) {
          this._portalConceal.cancel();
          const fn = this._invokeUnmounted;
          this._invokeUnmounted = null;
          // Install before invoking user lifecycle callbacks: they may reconnect
          // synchronously, before fn() even returns its disposal promise.
          if (split) this._splitOwnerDisposing = true;
          try {
            let disposed: void | Promise<void>;
            try {
              disposed = fn();
            } finally {
              unbindProtoInstance(this._instanceToken, this);
              this._controller = null;
              this._mountedOnce = false;
              this._pendingOwnedTokens = null;
            }
            await disposed;
          } finally {
            if (split) {
              this._splitOwnerDisposing = false;
              // Keep reconnect failures separate from a rejected disposal, and
              // recheck latest connectivity after repeated remove/append calls.
              queueMicrotask(() => {
                if (this.isConnected && !this._mountedOnce && !this._splitOwnerDisposing)
                  this.connectedCallback();
              });
            }
          }
          return;
        }
        unbindProtoInstance(this._instanceToken, this);
        this._controller = null;
        this._mountedOnce = false;
        this._pendingOwnedTokens = null;
      });
    }
  }

  if (register && !customElements.get(tagName)) {
    customElements.define(tagName, ProtoElement);
  }

  return ProtoElement as unknown as WebComponentAdapterConstructor<TProto>;
}

// packages/adapters/react/src/adapt.ts
import {
  getModuleDeclaration,
  type Prototype,
  type ScrollProjectionPreference,
} from '@proto.ui/core';
import type {
  CommitSignal,
  RuntimeCheckpoint,
  RuntimeController,
  RuntimeLifecycleEvent,
} from '@proto.ui/runtime';
import {
  createDeferredOwnerDisposal,
  createEventGate,
  createDefaultWebColorSchemeSource,
  createDefaultWebPreferenceSource,
  createDefaultWebStyleSupportSource,
  createScopedExposesReader,
  createViewEpochOwner,
  createWebProtoEventRouter,
  installViewVisibilityRule,
  PUI_VIEW_DETACHED_ATTR,
  PUI_VIEW_PENDING_ATTR,
  PUI_VIEW_REVEALING_ATTR,
  type ProtoAdapterProps,
  scheduleAfterWebLayout,
} from '@proto.ui/adapter-base';
import type { ExposeStateWebMode } from '@proto.ui/module-expose-state-web';
import {
  resolveWebTextControlLocalName,
  TEXT_CONTROL_DECLARATION,
} from '@proto.ui/module-text-control';
import { IMAGE_VIEW_DECLARATION, resolveWebImageLocalName } from '@proto.ui/module-image-view';
import {
  createZIndexOverlayLayerScheduler,
  type OverlayPort,
  type OverlayLayerScheduler,
  type OverlayZIndexLayerSchedulerOptions,
} from '@proto.ui/module-overlay';
import type { RawPropsSource } from '@proto.ui/module-props';
import { PropsBaseType } from '@proto.ui/types';

import { createDefaultMetaGetter } from './platform/meta';
import type { ProtoReactComponent, ReactAdapterHandle } from './types';
import {
  bindLogicalParent,
  bindLogicalEventTarget,
  createLogicalInstance,
  resolveLogicalTriggerEventRouteForTarget,
  markProtoInstance,
  unbindProtoInstance,
  unbindLogicalEventTarget,
} from './platform/instance-tree';
import { createReactEffectsPort } from './runtime/effects-port';
import { createReactModules, createReactOwnerModules } from './runtime/modules';
import { createReactHostSession } from './runtime/session';
import { renderTemplateToReact, type ReactRuntime as ReactRenderRuntime } from './template';

export { __REACT_PROTO_INSTANCE } from './platform/instance-tree';

export type ReactRuntime = ReactRenderRuntime & {
  useState: <T>(init: T) => [T, (next: T) => void];
  useRef: <T>(init: T) => { current: T };
  useEffect: (cb: () => void | (() => void), deps?: any[]) => void;
  useLayoutEffect: (cb: () => void | (() => void), deps?: any[]) => void;
  useImperativeHandle: (ref: any, create: () => any, deps?: any[]) => void;
  forwardRef: (render: (props: any, ref: any) => any) => any;
  createElement: (type: any, props?: any, ...children: any[]) => any;
  createPortal?: (children: any, container: Element) => any;
  createContext?: <T>(defaultValue: T) => { Provider: any };
  // Context is an opaque runtime handle to the adapter. Keeping the input
  // structural would incorrectly require React.useContext to accept a partial
  // Context object, which the real React type correctly rejects.
  useContext?: <T>(context: any) => T;
};

export type { ReactAdapterHandle } from './types';

export type ReactAdapterProps<Props extends PropsBaseType> = Props &
  PropsBaseType & {
    children?: any;
    className?: string;
    hostClassName?: string;
    surfaceClassName?: string;
    style?: any;
    hostStyle?: any;
    surfaceStyle?: any;
    [key: `on${string}`]: unknown;
  };

export interface ReactAdapterOptions<Props extends PropsBaseType> {
  schedule?: (task: () => void) => void;
  getProps?: (props: ReactAdapterProps<Props>) => Partial<Props> | null | undefined;
  getMeta?: (key: string) => unknown;
  diagnostics?: {
    onLifecycleEvent?: (event: RuntimeLifecycleEvent) => void;
    /** @deprecated Use onLifecycleEvent. */
    onLifecycleCheckpoint?: (cp: RuntimeCheckpoint) => void;
  };
  exposeStateWebMode?: ExposeStateWebMode;
  scrollProjection?: ScrollProjectionPreference;
  autoUpdateOnPropsChange?: boolean;
  rootTag?: string;
  overlayLayer?:
    | (OverlayZIndexLayerSchedulerOptions & {
        scheduler?: OverlayLayerScheduler;
      })
    | undefined;
}

type ReactRuntimeInput = ReactRuntime | { React: ReactRuntime };

function defaultGetProps<Props extends PropsBaseType>(
  props: ReactAdapterProps<Props>
): Partial<Props> {
  const {
    children,
    className,
    hostClassName,
    surfaceClassName,
    style,
    hostStyle,
    surfaceStyle,
    ...rest
  } = (props ?? {}) as any;
  const filtered: Record<string, unknown> = {};
  for (const [key, value] of Object.entries(rest)) {
    if (isFrameworkEventProp(key, value)) continue;
    filtered[key] = value;
  }
  return filtered as Partial<Props>;
}

function snapshotRawProps<Props extends PropsBaseType>(
  value: Partial<Props> | null | undefined
): Record<string, unknown> {
  return { ...(value ?? {}) };
}

function hasSameRawProps(
  previous: Readonly<Record<string, unknown>>,
  next: Readonly<Record<string, unknown>>
): boolean {
  const previousKeys = Object.keys(previous);
  const nextKeys = Object.keys(next);
  if (previousKeys.length !== nextKeys.length) return false;
  return previousKeys.every(
    (key) => Object.prototype.hasOwnProperty.call(next, key) && Object.is(previous[key], next[key])
  );
}

const MAX_FOCUS_TARGET_RETRIES = 3;
export function createReactAdapter(runtimeInput: ReactRuntimeInput) {
  const runtime = normalizeRuntime(runtimeInput);
  const sharedOverlayLayerScheduler = createZIndexOverlayLayerScheduler();
  const logicalOwnerContext = runtime.createContext?.<ReturnType<
    typeof createLogicalInstance
  > | null>(null);

  return function AdaptToReact<TProto extends Prototype<any, any>>(
    proto: TProto,
    opt: ReactAdapterOptions<ProtoAdapterProps<TProto>> = {}
  ): ProtoReactComponent<TProto> {
    type Props = ProtoAdapterProps<TProto>;
    const schedule = opt.schedule ?? ((task) => queueMicrotask(task));
    const getProps = opt.getProps ?? defaultGetProps;
    const getMeta = opt.getMeta ?? createDefaultMetaGetter();
    const colorSchemeSource = opt.getMeta ? undefined : createDefaultWebColorSchemeSource(getMeta);
    const preferenceSource = opt.getMeta ? undefined : createDefaultWebPreferenceSource(getMeta);
    const styleSupportSource = opt.getMeta
      ? undefined
      : createDefaultWebStyleSupportSource(getMeta);
    const exposeStateWebMode = opt.exposeStateWebMode;
    const scrollProjection = opt.scrollProjection;
    const autoUpdate = opt.autoUpdateOnPropsChange ?? true;
    const textControl = getModuleDeclaration(proto, TEXT_CONTROL_DECLARATION)?.config;
    const textControlRootTag = textControl
      ? resolveWebTextControlLocalName(textControl)
      : undefined;
    const imageView = getModuleDeclaration(proto, IMAGE_VIEW_DECLARATION)?.config;
    const imageViewRootTag = imageView ? resolveWebImageLocalName() : undefined;
    if (textControlRootTag && imageViewRootTag) {
      throw new Error(
        '[React Adapter] text-control and image-view declarations cannot share a root.'
      );
    }
    const declaredRootTag = textControlRootTag ?? imageViewRootTag;
    if (declaredRootTag && opt.rootTag && opt.rootTag !== declaredRootTag) {
      const declarationName = textControlRootTag ? 'text-control' : 'image-view';
      throw new Error(
        `[React Adapter] ${declarationName} declaration conflicts with rootTag: ${opt.rootTag}`
      );
    }
    const rootTag = declaredRootTag ?? opt.rootTag ?? 'div';
    const hasCustomOverlayLayerConfig =
      !!opt.overlayLayer &&
      (typeof opt.overlayLayer.baseZIndex !== 'undefined' ||
        typeof opt.overlayLayer.step !== 'undefined' ||
        typeof opt.overlayLayer.roleOffsets !== 'undefined');
    const overlayLayerScheduler =
      opt.overlayLayer?.scheduler ??
      (hasCustomOverlayLayerConfig
        ? createZIndexOverlayLayerScheduler({
            baseZIndex: opt.overlayLayer?.baseZIndex,
            step: opt.overlayLayer?.step,
            roleOffsets: opt.overlayLayer?.roleOffsets,
          })
        : sharedOverlayLayerScheduler);

    const Component = runtime.forwardRef((props: ReactAdapterProps<Props>, ref: any) => {
      const rootRef = runtime.useRef<HTMLElement | null>(null);
      const instanceTokenRef = runtime.useRef(createLogicalInstance(proto as Prototype<any>));
      const parentToken =
        logicalOwnerContext && runtime.useContext
          ? (runtime.useContext(logicalOwnerContext) as ReturnType<
              typeof createLogicalInstance
            > | null)
          : null;
      const supportsOwnerContext = !!logicalOwnerContext && !!runtime.useContext;
      if (logicalOwnerContext && runtime.useContext) {
        bindLogicalParent(instanceTokenRef.current, parentToken);
      }
      const [renderChildren, setRenderChildren] = runtime.useState<any>(null);
      const hostTokenRevisionRef = runtime.useRef(0);
      const [hostStyle, setHostStyle] = runtime.useState<{ tokens: string[]; revision: number }>({
        tokens: [],
        revision: 0,
      });
      const setHostTokens = (tokens: string[]) => {
        const revision = ++hostTokenRevisionRef.current;
        setHostStyle({ tokens, revision });
      };
      const [shouldExist, setShouldExist] = runtime.useState(!supportsOwnerContext);
      const viewEffectsTargetReadyRef = runtime.useRef(false);
      const viewReadyRef = runtime.useRef(false);
      const focusTargetReadyListenersRef = runtime.useRef<Set<() => void>>(new Set());
      const focusTargetRetryScheduledRef = runtime.useRef(false);
      const focusTargetRetryCountRef = runtime.useRef(0);
      const notifyFocusTargetReady = () => {
        const target = rootRef.current;
        if (!viewReadyRef.current || !target?.isConnected) return;
        for (const listener of Array.from(focusTargetReadyListenersRef.current)) listener();
        if (target.ownerDocument.activeElement === target) focusTargetRetryCountRef.current = 0;
      };

      const controllerRef = runtime.useRef<RuntimeController | null>(null);
      const eventGateRef = runtime.useRef<ReturnType<typeof createEventGate> | null>(null);
      const exposesRef = runtime.useRef<Record<string, unknown>>({});
      const invokeInCallbackScopeRef = runtime.useRef<((fn: () => void) => void) | null>(null);
      const scopedExposesReaderRef = runtime.useRef(
        createScopedExposesReader(() => invokeInCallbackScopeRef.current)
      );

      const propsRef = runtime.useRef<ReactAdapterProps<Props>>(props);
      propsRef.current = props;
      const eventCallbacksRef = runtime.useRef<Record<string, (payload?: unknown) => void>>({});
      eventCallbacksRef.current = collectEventCallbacks(props);

      const subsRef = runtime.useRef<Set<() => void>>(new Set());
      const rawPropsSourceRef = runtime.useRef<RawPropsSource<Props> | null>(null);
      const deliveredRawPropsRef = runtime.useRef<Record<string, unknown> | null>(null);

      const pendingCommitRef = runtime.useRef(false);
      const pendingSignalRef = runtime.useRef<CommitSignal | null>(null);
      const commitVersionRef = runtime.useRef(0);
      const [commitVersion, setCommitVersion] = runtime.useState(0);
      const pendingRevealStyleRevisionRef = runtime.useRef<number | null>(null);
      const revealGenerationRef = runtime.useRef(0);
      const hostSessionRef = runtime.useRef<ReturnType<
        typeof createReactHostSession<Props>
      > | null>(null);
      const ownerRef = runtime.useRef<ReturnType<typeof createViewEpochOwner<Props>> | null>(null);
      if (!ownerRef.current) {
        ownerRef.current = createViewEpochOwner<Props>({ prototypeName: proto.name });
      }
      const ownerDisposalRef = runtime.useRef<ReturnType<
        typeof createDeferredOwnerDisposal
      > | null>(null);
      if (!ownerDisposalRef.current) {
        ownerDisposalRef.current = createDeferredOwnerDisposal(() => ownerRef.current?.dispose());
      }
      const boundRootRef = runtime.useRef<HTMLElement | null>(null);

      if (!rawPropsSourceRef.current) {
        rawPropsSourceRef.current = {
          debugName: `${proto.name}#raw-props`,
          get() {
            const nextProps = getProps(propsRef.current) ?? ({} as Partial<Props>);
            return nextProps as Readonly<Props & PropsBaseType>;
          },
          subscribe(cb) {
            subsRef.current.add(cb);
            return () => subsRef.current.delete(cb);
          },
        };
      }

      runtime.useImperativeHandle(
        ref,
        () => ({
          update: () => controllerRef.current?.update(),
          getExposes: () => scopedExposesReaderRef.current.read(exposesRef.current ?? {}),
          invokeInCallbackScope: (fn: () => void) => invokeInCallbackScopeRef.current?.(fn),
        }),
        []
      );

      runtime.useEffect(() => {
        const nextRawProps = snapshotRawProps(getProps(propsRef.current));
        const previousRawProps = deliveredRawPropsRef.current;
        deliveredRawPropsRef.current = nextRawProps;
        if (previousRawProps && hasSameRawProps(previousRawProps, nextRawProps)) return;

        for (const cb of subsRef.current) cb();
        if (autoUpdate) controllerRef.current?.update();
      }, [props, autoUpdate]);

      const createHostSession = (
        wiring: Parameters<typeof createReactHostSession<Props>>[0]['wiring'],
        initialMount: 'eager' | 'manual'
      ) =>
        createReactHostSession({
          proto,
          schedule,
          rawPropsSource: rawPropsSourceRef.current as RawPropsSource<Props>,
          wiring,
          eventGate: {
            disable: () => eventGateRef.current?.disable(),
            dispose: () => ownerRef.current?.disposeView(),
          },
          router: {
            dispose: () => ownerRef.current?.disposeView(),
          },
          onLifecycleCheckpoint: opt.diagnostics?.onLifecycleCheckpoint,
          onLifecycleEvent: opt.diagnostics?.onLifecycleEvent,
          onCommit: (children, signal) => {
            pendingCommitRef.current = true;
            pendingSignalRef.current = signal;
            setRenderChildren(children);
            commitVersionRef.current += 1;
            setCommitVersion(commitVersionRef.current);
          },
          onAfterUnmount: () => {
            scopedExposesReaderRef.current.invalidate();
            invokeInCallbackScopeRef.current = null;
            hostSessionRef.current = null;
            controllerRef.current = null;
            exposesRef.current = {};
            setHostTokens([]);
          },
          initialMount,
        });

      runtime.useLayoutEffect(() => {
        if (!supportsOwnerContext) return;
        let hostSession = ownerRef.current?.session;
        if (!hostSession) {
          const ownerModules = createReactOwnerModules({
            instanceToken: instanceTokenRef.current,
            emit: (key, payload) => {
              eventCallbacksRef.current[key]?.(payload);
            },
            rawPropsSource: rawPropsSourceRef.current as RawPropsSource<Props>,
            getMeta,
            colorSchemeSource,
            preferenceSource,
            styleSupportSource,
            setExposes: (record) => {
              exposesRef.current = record;
            },
            runInCallbackScope: (fn) => {
              const invoke = invokeInCallbackScopeRef.current;
              if (invoke) invoke(fn);
              else fn();
            },
            overlayLayerScheduler,
          });
          hostSession = ownerRef.current!.initialize({
            modules: ownerModules,
            createSession: (wiring) => createHostSession(wiring, 'manual'),
            onViewIntent: (snapshot) => {
              setShouldExist(snapshot.present);
            },
          });
        }

        hostSessionRef.current = hostSession as ReturnType<typeof createReactHostSession<Props>>;
        controllerRef.current = hostSession.controller as RuntimeController;
        invokeInCallbackScopeRef.current = hostSession.invokeInCallbackScope;
        const initialIntent = hostSession.viewIntent.getSnapshot();
        setShouldExist(initialIntent.present);
      }, []);

      runtime.useLayoutEffect(() => {
        if (!shouldExist) {
          const detachedEl = rootRef.current;
          if (detachedEl) installViewVisibilityRule(detachedEl.ownerDocument);
          detachedEl?.setAttribute(PUI_VIEW_PENDING_ATTR, '');
          revealGenerationRef.current += 1;
          detachedEl?.removeAttribute(PUI_VIEW_REVEALING_ATTR);
          eventGateRef.current?.disable?.();
          if (ownerRef.current?.hasView) void ownerRef.current.detachView();
          setHostTokens([]);
          pendingRevealStyleRevisionRef.current = null;
          viewEffectsTargetReadyRef.current = false;
          viewReadyRef.current = false;
          focusTargetRetryCountRef.current = 0;
          return;
        }

        const rootEl = rootRef.current;
        if (!rootEl) return;

        installViewVisibilityRule(rootEl.ownerDocument);

        markProtoInstance(rootEl, proto as Prototype<any>, instanceTokenRef.current);
        boundRootRef.current = rootEl;

        const eventGate = createEventGate();
        eventGateRef.current = eventGate;

        const router = createWebProtoEventRouter({
          rootEl,
          instanceToken: instanceTokenRef.current,
          resolveSemanticEventRoute: resolveLogicalTriggerEventRouteForTarget,
          globalEl: typeof window === 'undefined' ? rootEl : window,
          isEnabled: () => eventGate.isEnabled?.() ?? true,
        });
        bindLogicalEventTarget(instanceTokenRef.current, router.rootTarget);
        let viewDisposed = false;
        const disposeView = () => {
          if (viewDisposed) return;
          viewDisposed = true;
          eventGate.disable();
          eventGate.dispose();
          unbindLogicalEventTarget(instanceTokenRef.current, router.rootTarget);
          router.dispose();
          unbindProtoInstance(instanceTokenRef.current, boundRootRef.current ?? undefined);
          if (boundRootRef.current === rootEl) boundRootRef.current = null;
          if (eventGateRef.current === eventGate) eventGateRef.current = null;
        };

        const effectsPort = createReactEffectsPort((tokens) => {
          setHostTokens(tokens);
        });

        const rawPropsSource = rawPropsSourceRef.current as RawPropsSource<Props>;
        const modules = createReactModules({
          el: rootEl,
          instanceToken: instanceTokenRef.current,
          router,
          emit: (key, payload) => {
            eventCallbacksRef.current[key]?.(payload);
          },
          rawPropsSource,
          effectsPort,
          getMeta,
          colorSchemeSource,
          preferenceSource,
          styleSupportSource,
          exposeStateWebMode,
          scrollProjection,
          setExposes: (record) => {
            exposesRef.current = record;
          },
          runInCallbackScope: (fn) => {
            const invoke = invokeInCallbackScopeRef.current;
            if (invoke) {
              invoke(fn);
              return;
            }
            fn();
          },
          // A child of a detached ancestor still mounts and attaches its own
          // view, so readiness has to consult the subtree, not just this host.
          // A pending update also gates host events. Native focus must wait
          // until its observer is effective, or DOM focus can apply without
          // updating the Focus facts used by keyboard navigation.
          isViewReady: () =>
            viewEffectsTargetReadyRef.current &&
            eventGate.isEnabled() &&
            !rootRef.current?.closest(`[${PUI_VIEW_DETACHED_ATTR}]`),
          getCurrentElement: () => rootRef.current,
          subscribeTargetReady: (listener) => {
            focusTargetReadyListenersRef.current.add(listener);
            return () => focusTargetReadyListenersRef.current.delete(listener);
          },
          retryTargetReady: () => {
            if (
              focusTargetRetryScheduledRef.current ||
              focusTargetRetryCountRef.current >= MAX_FOCUS_TARGET_RETRIES
            ) {
              return;
            }
            focusTargetRetryScheduledRef.current = true;
            focusTargetRetryCountRef.current += 1;
            scheduleAfterWebLayout(
              rootRef.current,
              () => {
                focusTargetRetryScheduledRef.current = false;
                notifyFocusTargetReady();
              },
              schedule
            );
          },
          overlayLayerScheduler,
        });

        const hostSession = ownerRef.current!.attachView({
          modules,
          disposeView,
          createSession: (wiring) => createHostSession(wiring, 'eager'),
        });

        hostSessionRef.current = hostSession;
        controllerRef.current = hostSession.controller as RuntimeController;
        invokeInCallbackScopeRef.current = hostSession.invokeInCallbackScope;

        const { kernel } = hostSession;
        if (kernel && kernel.run) {
          (kernel.run as any).host = { get: () => rootRef.current };
        }
      }, [shouldExist]);

      // React StrictMode replays layout effects. Detach immediately so view
      // resources follow the replay, but defer terminal owner disposal by one
      // microtask so an immediate retain can preserve the Proto instance.
      runtime.useLayoutEffect(() => {
        ownerDisposalRef.current?.retain();
        return () => {
          pendingRevealStyleRevisionRef.current = null;
          viewEffectsTargetReadyRef.current = false;
          viewReadyRef.current = false;
          focusTargetRetryCountRef.current = 0;
          const cleanupRoot = rootRef.current;
          cleanupRoot?.setAttribute(PUI_VIEW_PENDING_ATTR, '');
          revealGenerationRef.current += 1;
          cleanupRoot?.removeAttribute(PUI_VIEW_REVEALING_ATTR);
          void ownerRef.current?.detachView();
          ownerDisposalRef.current?.release();
        };
      }, []);

      runtime.useLayoutEffect(() => {
        if (pendingCommitRef.current) {
          pendingCommitRef.current = false;
          const wasReady = viewReadyRef.current;
          const signal = pendingSignalRef.current;
          pendingSignalRef.current = null;
          viewEffectsTargetReadyRef.current = true;

          // Runtime finalizes rule-driven view effects from CommitSignal.done().
          // Keep a newly attached root pending until that flush has reached a
          // later React DOM commit; otherwise the base style becomes visible
          // before its variant, size, and state tokens.
          signal?.done?.();

          if (wasReady) {
            if (!pendingCommitRef.current) {
              eventGateRef.current?.enable();
              notifyFocusTargetReady();
            }
            return;
          }

          pendingRevealStyleRevisionRef.current = hostTokenRevisionRef.current;
        }

        const requiredStyleRevision = pendingRevealStyleRevisionRef.current;
        if (requiredStyleRevision === null) return;
        if (
          hostStyle.revision < requiredStyleRevision ||
          hostStyle.revision !== hostTokenRevisionRef.current
        ) {
          return;
        }

        pendingRevealStyleRevisionRef.current = null;
        viewReadyRef.current = true;
        focusTargetRetryCountRef.current = 0;
        const revealedRoot = rootRef.current;
        const revealGeneration = ++revealGenerationRef.current;
        revealedRoot?.setAttribute(PUI_VIEW_REVEALING_ATTR, '');
        revealedRoot?.removeAttribute(PUI_VIEW_PENDING_ATTR);
        if (revealedRoot) {
          scheduleAfterWebLayout(
            revealedRoot,
            () => {
              if (
                revealGenerationRef.current === revealGeneration &&
                rootRef.current === revealedRoot &&
                !revealedRoot.hasAttribute(PUI_VIEW_PENDING_ATTR)
              ) {
                revealedRoot.removeAttribute(PUI_VIEW_REVEALING_ATTR);
              }
            },
            schedule
          );
        }
        eventGateRef.current?.enable();
        notifyFocusTargetReady();
      }, [commitVersion, hostStyle.revision]);

      // A renderer can replace the host element after the Proto commit that
      // first announced readiness. Re-advertise the current ref after every
      // committed render, then once more after the renderer's microtask work,
      // so pending focus requests bind to the element that actually survived.
      runtime.useLayoutEffect(() => {
        const target = rootRef.current;
        if (!viewReadyRef.current || !target?.isConnected) return;
        notifyFocusTargetReady();
        schedule(() => {
          if (rootRef.current === target) notifyFocusTargetReady();
        });
      });

      const rendered = renderTemplateToReact(runtime, renderChildren, {
        slot: props.children,
      });
      // Template roots are a static child list. Passing that list as one array
      // makes React treat it as a dynamic collection and warn that anatomy
      // siblings such as Select Value + Chevron need authored keys.
      const renderedChildren = Array.isArray(rendered) ? rendered : [rendered];

      const overlayPort = ownerRef.current?.session?.caps.getPort<OverlayPort>('overlay');
      const portalContainer =
        shouldExist &&
        overlayPort?.getConfig().portal === true &&
        typeof runtime.createPortal === 'function' &&
        typeof document !== 'undefined'
          ? document.body
          : null;

      // Overlay content is detached, not unmounted, when it is not present: the
      // host element and the authored children stay put so collection members
      // keep registering, and the shared detached rule takes them out of paint,
      // a11y, and tab order. Prototypes that drive presence directly through
      // `lifecycle.setPresent`, such as Tabs Content, keep unmounting.
      const detached = !shouldExist && overlayPort?.hasPresenceBinding() === true;
      const content =
        !shouldExist && !detached
          ? null
          : runtime.createElement(
              rootTag,
              {
                ref: rootRef as { current: HTMLElement | null },
                className: mergeHostClassName([
                  props.surfaceClassName,
                  props.hostClassName,
                  props.className,
                ]),
                style: mergeHostStyle([props.surfaceStyle, props.hostStyle, props.style]),
                'data-pui-root': '',
                [PUI_VIEW_DETACHED_ATTR]: detached ? '' : undefined,
                [PUI_VIEW_PENDING_ATTR]: viewReadyRef.current ? undefined : '',
                'data-pui-style': serializeStyleTokens(hostStyle.tokens),
                'data-demo-ref': props['data-demo-ref' as keyof typeof props] as string | undefined,
              },
              // Without a view there is no template to place the slot into, so the
              // authored children stand in for it.
              ...(shouldExist ? renderedChildren : [props.children])
            );
      const projectedContent = portalContainer
        ? runtime.createPortal!(content, portalContainer)
        : content;
      if (!logicalOwnerContext) return projectedContent;
      return runtime.createElement(
        logicalOwnerContext.Provider,
        { value: instanceTokenRef.current },
        projectedContent
      );
    }) as ProtoReactComponent<TProto>;

    Component.displayName = `Proto(${proto.name})`;
    return Component;
  };
}

function normalizeRuntime(input: ReactRuntimeInput): ReactRuntime {
  return (input as any).React ?? (input as ReactRuntime);
}

function mergeHostClassName(input: unknown) {
  const values = (Array.isArray(input) ? input : [input])
    .map((value: any) => (typeof value === 'string' ? value.trim() : value))
    .filter((value: any) => {
      if (typeof value === 'string') return value.length > 0;
      return value != null;
    });

  const seen = new Set<string>();
  const out: string[] = [];

  for (const value of values) {
    if (typeof value !== 'string') continue;
    for (const token of value.split(/\s+/)) {
      if (!token || seen.has(token)) continue;
      seen.add(token);
      out.push(token);
    }
  }

  return out.length > 0 ? out.join(' ') : undefined;
}

function mergeHostStyle(input: unknown) {
  const values = (Array.isArray(input) ? input : [input])
    .flatMap((value) => {
      if (value == null || value === '') return [];
      return Array.isArray(value) ? value : [value];
    })
    .filter((value) => {
      if (value == null || value === '') return false;
      if (typeof value === 'object') return Object.keys(value as object).length > 0;
      return String(value).trim().length > 0;
    });

  if (values.length === 0) return undefined;
  if (values.length === 1) return values[0];
  return values;
}

function serializeStyleTokens(tokens: string[]) {
  return tokens.length > 0 ? tokens.join(' ') : undefined;
}

function collectEventCallbacks(
  props: Record<string, unknown>
): Record<string, (payload?: unknown) => void> {
  const out: Record<string, (payload?: unknown) => void> = {};
  for (const [key, value] of Object.entries(props)) {
    if (!isFrameworkEventProp(key, value)) continue;
    const eventKey = fromHandlerPropName(key);
    if (!eventKey) continue;
    out[eventKey] = value as (payload?: unknown) => void;
  }
  return out;
}

function isFrameworkEventProp(key: string, value: unknown) {
  return /^on[A-Z]/.test(key) && typeof value === 'function';
}

function fromHandlerPropName(key: string) {
  const raw = key.slice(2);
  if (!raw) return null;
  return raw[0]!.toLowerCase() + raw.slice(1);
}
